### PR TITLE
Refactor: Jump command should have shorter cooldown

### PR DESCRIPTION
**Pull request by durgeshahire07**
Issue #81 
Modified the related line to 5 seconds instead of 15.

### CODE REVIEW

**Review by KL13NT — APPROVED** [review]

**Comment by KL13NT** [comment]
Hey @durgeshahire07, thanks for contributing to valbot! To keep our commit history consistent please amend your commit to be in lower-case by running `git commit --amend -m "refactor: jump command's cooldown made short"` and then force push to your branch `git push origin master -f`. I'll merge it as soon as you do this. Thanks!

**Comment by KL13NT** [comment]
Looks like you also signed your commit, great work! Looks good to me. There are other open issues for Hacktoberfest if you wish to contribute more. Your name will be added to the contributors list on this repo. 

Thanks for contributing to Valbot! 🥳

**Comment by KL13NT** [comment]
@all-contributors please add @durgeshahire07 for code

**Comment by durgeshahire07** [comment]
Thank you so much @KL13NT

**Pull request merged**
